// shape_geometry.h — the one place shape outlines are constructed and measured.
//
// Two jobs, deliberately in one file because they are the same fact viewed twice:
//
//   BuildShapePath  — (kind, bounds, parameters) -> outline
//   MeasurePathData — outline -> the box that exactly contains it
//
// Why this exists at all. Until now the engine could not construct geometry: it
// received a pre-built SVG `d` string from TypeScript and parsed it. That is
// workable for a committed document and impossible for a live creation preview,
// because the preview has to be regenerated on every pointer sample and the only
// way to get new geometry across the boundary was `loadScene`, which replaces the
// entire scene, resets the node index, cancels any gesture and forces a full
// repaint. Sixty of those a second is exactly what the damage-tracking work
// removed.
//
// With the builder here, a creation gesture ships two doubles per frame and the
// engine produces the outline, so the preview the user drags is generated by the
// same code that will produce the committed object. `preview == final` is then a
// property of the architecture rather than something two implementations have to
// agree on.
//
// MeasurePathData is the cross-check for the TypeScript `exactPathBounds`. The
// selection box is drawn from a node's local bounds, and those bounds used to be
// a *superset* (control points included, arcs expanded by their radii) or, for a
// parametric shape, simply *asserted*. Both put the box away from the shape. Skia
// already knows the answer exactly; this exposes it so the parity suite can hold
// the TypeScript measurement to it.
//
// Nothing here silently substitutes. An unknown shape kind, a degenerate box or
// unparsable path data is reported to the caller.
//
// One responsibility per file: constructing and measuring shape outlines.

#ifndef PYDEE_SHAPE_GEOMETRY_H_
#define PYDEE_SHAPE_GEOMETRY_H_

#include <optional>
#include <string>
#include <string_view>

#include "pydee/geometry.h"

namespace pydee {

/**
 * The shape vocabulary, matching the editor's own shape types.
 *
 * An enum rather than a string at the point of use, so an unrecognised type is
 * rejected once, at parse time, instead of producing an empty outline several
 * layers deeper — which is how an unregistered parametric type used to end up as
 * a fully selectable layer that painted nothing.
 */
enum class ShapeKind {
  kRectangle,
  kRoundedRect,
  kEllipse,
  kTriangle,
  kDiamond,
  kPentagon,
  kHexagon,
  kOctagon,
  kStar,
  kBadge,
  kCross,
  kHeart,
  kDonut,
  kChatBubble,
  kBanner,
  kShield,
  kLine,
  kArrow,
};

/** The wire name of a kind, so both sides speak one vocabulary. */
const char* ShapeKindName(ShapeKind kind);

/** Parse a wire name, or nullopt when the kind is not supported. */
std::optional<ShapeKind> ParseShapeKind(std::string_view name);

/**
 * Shape parameters, with the editor's defaults.
 *
 * All ratios, never absolute lengths, so a shape's proportions survive a resize
 * without the parameters needing to be rescaled — which is what stops a repeated
 * resize from compounding.
 */
struct ShapeParameters {
  /** Star/badge point count. Values below 3 are rejected. */
  int point_count = 5;
  /** Star/badge inner radius as a fraction of the outer radius. */
  double inner_ratio = 0.382;
  /** Corner radius as a fraction of min(width, height). */
  double corner_ratio = 0.2;
  /** Cross arm thickness as a fraction of min(width, height). */
  double thickness_ratio = 0.33;
  /** Donut hole radius as a fraction of the outer radius. */
  double hole_ratio = 0.5;
  /** Arrow head length as a fraction of the total length. */
  double head_ratio = 0.3;
};

/** Why an outline could not be built. Never a silent empty path. */
enum class ShapeBuildFailure {
  /** The kind is not in the vocabulary. */
  kUnknownKind,
  /** Width or height is zero, so there is no shape to build. */
  kDegenerateBounds,
  /** A parameter is out of range (a star with two points, a negative ratio). */
  kInvalidParameters,
  /** A coordinate came out NaN or infinite. */
  kNonFiniteGeometry,
};

const char* ShapeBuildFailureName(ShapeBuildFailure failure);

/**
 * The outline of `kind` filling `bounds`, as SVG path data.
 *
 * `bounds` may have negative extents: a creation drag that runs right-to-left or
 * bottom-to-top is normal, and normalising here rather than at every call site is
 * what keeps a backwards drag from producing a mirrored or empty shape.
 *
 * Every kind FILLS its box on both axes. That is a deliberate difference from the
 * TypeScript generators it replaces, where a star and a badge were inscribed in a
 * circle of radius min(w, h)/2: stretching the drag box horizontally left the
 * shape square and only moved it, so the outline did not follow the gesture and
 * the box did not fit the outline. Filling the box makes stretching visible, which
 * is the behaviour a creation preview has to show.
 *
 * Returns false and sets `failure` rather than emitting an empty string.
 */
bool BuildShapePath(ShapeKind kind,
                    const RectF& bounds,
                    const ShapeParameters& parameters,
                    std::string* out_path_data,
                    ShapeBuildFailure* failure);

/**
 * The exact box containing `path_data`, via Skia.
 *
 * Tight, not conservative: every returned edge is touched by the outline. Returns
 * false when the data parses to nothing, which is a different fact from a
 * zero-size shape at the origin.
 */
bool MeasurePathData(const std::string& path_data, RectF* out);

}  // namespace pydee

#endif  // PYDEE_SHAPE_GEOMETRY_H_
